apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-volume
  namespace: kingdon
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  # storageClassName: aws-gp2-dynamic
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
