apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak-testing
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m30s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: fleet-testing
  path: ./apps/keycloak
  dependsOn: []
  # - name: 11-certificates
  # - name: 20-my-secrets
  # - name: 30-ingress-nginx
  prune: true
 #wait: true
  suspend: false
  validation: server
