apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- ../../apps/root
images:
- name: ghcr.io/fluxcd/kustomize-controller
  newName: somma/kustomize-controller
  newTag: rc-f7e83795a4f
